-- SELECT * FROM FILM ORDER BY RATING; --Q.1

-- SELECT COUNT(REPLACEMENT_COST),
-- 	REPLACEMENT_COST
-- FROM FILM
-- GROUP BY REPLACEMENT_COST
-- HAVING COUNT(REPLACEMENT_COST) > 50; --Q.2


--SELECT COUNT(store_id),store_id FROM customer GROUP BY store_id; --Q.3

--SELECT COUNT(city), country_id FROM city GROUP BY country_id ORDER BY COUNT(*) DESC LIMIT 1 ; -- Q.4

-- ALP OZKAN
