--SELECT AVG (rental_rate) From film; --Q.1
--SELECT COUNT(title) FROM film WHERE title LIKE 'C%'; --Q.2
--SELECT MAX(length) FROM film WHERE rental_rate = 0.99; --Q.3
--SELECT  COUNT(DISTINCT(replacement_cost)) FROM film WHERE length> 150 ; --Q.4
--ALP OZKAN
